apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
      - name: ECR
        api_url: https://<AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com
        prefix: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com
        credentials: ext:/app/scripts/ecr-login.sh
        credsexpire: 10h
  ecr-login.sh: |
    #!/bin/sh
    aws ecr --region <REGION> get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
  test.sh: |
    #!/bin/sh
    aws s3 ls
