apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
spec:
  template:
    spec:
      containers:
        - name: argocd-image-updater
          volumeMounts:
            - name: ecr-login-script
              mountPath: /app/scripts
            - name: aws-config
              mountPath: /tmp/.aws
          env:
            - name: AWS_CONFIG_FILE
              value: /tmp/.aws/config
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /tmp/.aws/credentials
            - name: HOME
              value: /tmp

      volumes:
        - name: ecr-login-script
          configMap:
            defaultMode: 0755
            items:
              - key: ecr-login.sh
                path: ecr-login.sh
            name: argocd-image-updater-config
            optional: true
        - name: aws-config
          emptyDir: {}
