apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
patchesStrategicMerge:
  - configmap.yaml # ConfigMap
  - deployment.yaml # Deployment
  - service_account.yaml # ServiceAccount
