apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: my-image=<AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<ECR_REPO_NAME>:latest
    argocd-image-updater.argoproj.io/my-image.update-strategy: digest
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize
    repoURL: https://github.com/yuu-misaki/argocd-fastapi.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
